msmykowski@device-1870 ~/studia/lab6-nodejs_michal_s (main >) $ git push
Enumerating objects: 6, done.
Counting objects: 100% (6/6), done.
Delta compression using up to 12 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (5/5), 623 bytes | 623.00 KiB/s, done.
Total 5 (delta 1), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
To https://github.com/smyk-git/lab6-nodejs_michal_s.git
 ! [remote rejected] main -> main (refusing to allow a Personal Access Token to create or update workflow `.github/workflows/ci.yml` without `workflow` scope)
error: failed to push some refs to 'https://github.com/smyk-git/lab6-nodejs_michal_s.git'
 ! msmykowski@device-1870 ~/studia/lab6-nodejs_michal_s (main >) $
